"""
Provision the us_area_code_timezones reference table (Dev 1 plan, Week 1
Subtask 1.2.2 — Quiet Hours).

Global, non-tenant reference data (same category as counties — NOT added
to config/tenant_policies.py). Maps a US NANP phone area code to the IANA
timezone used to compute "is it currently quiet hours (9pm-8am) for this
recipient". A phone whose area code still isn't in this table (a future
NANP assignment, a non-US/non-NANP number) fails closed
(src/services/campaign_readiness_gate.py withholds SMS eligibility rather
than assuming it's not quiet hours) — but that's now the rare exception,
not the common case: this seeds all 298 currently assigned US area codes.

Generated from ravisorg/Area-Code-Geolocation-Database's
us-area-code-cities.csv (NANPA-sourced city/state/lat/long per area code,
filtered to country=US), resolved to an IANA timezone per city via
timezonefinder's polygon lookup (majority vote across an area code's
cities) rather than a hand-maintained state mapping — the tz database's
own boundaries already encode the cases a simple state lookup gets wrong
(Florida panhandle 850 -> Central, not Eastern; Texas's El Paso 915 ->
Mountain, not Central; Indiana's split Eastern/Central counties; Arizona's
602/480/520/623/928 -> America/Phoenix, which observes no DST unlike the
rest of the Mountain zone). Extend SEED_AREA_CODES and re-run to add a
newly assigned code; the INSERT is idempotent (ON CONFLICT DO NOTHING).

Idempotent: CREATE TABLE IF NOT EXISTS, seed insert is ON CONFLICT DO NOTHING.

    PYTHONPATH=. python migrations/apply_area_code_timezones.py
"""
import sys

sys.path.insert(0, ".")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from sqlalchemy import text

from src.core.database import get_owner_db_context

DDL = [
	"""
	CREATE TABLE IF NOT EXISTS us_area_code_timezones (
		area_code     VARCHAR(3)   PRIMARY KEY,
		iana_timezone VARCHAR(50)  NOT NULL
	)
	""",
	"GRANT SELECT ON us_area_code_timezones TO blackink_app",
	"GRANT SELECT ON us_area_code_timezones TO blackink_system",
]

# All 298 currently NANPA-assigned US area codes, resolved to an IANA
# timezone as described in the module docstring above.
SEED_AREA_CODES = [
	{"area_code": "201", "iana_timezone": "America/New_York"},
	{"area_code": "202", "iana_timezone": "America/New_York"},
	{"area_code": "203", "iana_timezone": "America/New_York"},
	{"area_code": "205", "iana_timezone": "America/Chicago"},
	{"area_code": "206", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "207", "iana_timezone": "America/New_York"},
	{"area_code": "208", "iana_timezone": "America/Boise"},
	{"area_code": "209", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "210", "iana_timezone": "America/Chicago"},
	{"area_code": "212", "iana_timezone": "America/New_York"},
	{"area_code": "213", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "214", "iana_timezone": "America/Chicago"},
	{"area_code": "215", "iana_timezone": "America/New_York"},
	{"area_code": "216", "iana_timezone": "America/New_York"},
	{"area_code": "217", "iana_timezone": "America/Chicago"},
	{"area_code": "218", "iana_timezone": "America/Chicago"},
	{"area_code": "219", "iana_timezone": "America/Chicago"},
	{"area_code": "220", "iana_timezone": "America/New_York"},
	{"area_code": "224", "iana_timezone": "America/Chicago"},
	{"area_code": "225", "iana_timezone": "America/Chicago"},
	{"area_code": "228", "iana_timezone": "America/Chicago"},
	{"area_code": "229", "iana_timezone": "America/New_York"},
	{"area_code": "231", "iana_timezone": "America/Detroit"},
	{"area_code": "234", "iana_timezone": "America/New_York"},
	{"area_code": "239", "iana_timezone": "America/New_York"},
	{"area_code": "240", "iana_timezone": "America/New_York"},
	{"area_code": "248", "iana_timezone": "America/Detroit"},
	{"area_code": "251", "iana_timezone": "America/Chicago"},
	{"area_code": "252", "iana_timezone": "America/New_York"},
	{"area_code": "253", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "254", "iana_timezone": "America/Chicago"},
	{"area_code": "256", "iana_timezone": "America/Chicago"},
	{"area_code": "260", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "262", "iana_timezone": "America/Chicago"},
	{"area_code": "267", "iana_timezone": "America/New_York"},
	{"area_code": "269", "iana_timezone": "America/Detroit"},
	{"area_code": "270", "iana_timezone": "America/Chicago"},
	{"area_code": "272", "iana_timezone": "America/New_York"},
	{"area_code": "276", "iana_timezone": "America/New_York"},
	{"area_code": "281", "iana_timezone": "America/Chicago"},
	{"area_code": "301", "iana_timezone": "America/New_York"},
	{"area_code": "302", "iana_timezone": "America/New_York"},
	{"area_code": "303", "iana_timezone": "America/Denver"},
	{"area_code": "304", "iana_timezone": "America/New_York"},
	{"area_code": "305", "iana_timezone": "America/New_York"},
	{"area_code": "307", "iana_timezone": "America/Denver"},
	{"area_code": "308", "iana_timezone": "America/Chicago"},
	{"area_code": "309", "iana_timezone": "America/Chicago"},
	{"area_code": "310", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "312", "iana_timezone": "America/Chicago"},
	{"area_code": "313", "iana_timezone": "America/Detroit"},
	{"area_code": "314", "iana_timezone": "America/Chicago"},
	{"area_code": "315", "iana_timezone": "America/New_York"},
	{"area_code": "316", "iana_timezone": "America/Chicago"},
	{"area_code": "317", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "318", "iana_timezone": "America/Chicago"},
	{"area_code": "319", "iana_timezone": "America/Chicago"},
	{"area_code": "320", "iana_timezone": "America/Chicago"},
	{"area_code": "321", "iana_timezone": "America/New_York"},
	{"area_code": "323", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "325", "iana_timezone": "America/Chicago"},
	{"area_code": "330", "iana_timezone": "America/New_York"},
	{"area_code": "331", "iana_timezone": "America/Chicago"},
	{"area_code": "334", "iana_timezone": "America/Chicago"},
	{"area_code": "336", "iana_timezone": "America/New_York"},
	{"area_code": "337", "iana_timezone": "America/Chicago"},
	{"area_code": "339", "iana_timezone": "America/New_York"},
	{"area_code": "346", "iana_timezone": "America/Chicago"},
	{"area_code": "347", "iana_timezone": "America/New_York"},
	{"area_code": "351", "iana_timezone": "America/New_York"},
	{"area_code": "352", "iana_timezone": "America/New_York"},
	{"area_code": "360", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "361", "iana_timezone": "America/Chicago"},
	{"area_code": "364", "iana_timezone": "America/Chicago"},
	{"area_code": "385", "iana_timezone": "America/Denver"},
	{"area_code": "386", "iana_timezone": "America/New_York"},
	{"area_code": "401", "iana_timezone": "America/New_York"},
	{"area_code": "402", "iana_timezone": "America/Chicago"},
	{"area_code": "404", "iana_timezone": "America/New_York"},
	{"area_code": "405", "iana_timezone": "America/Chicago"},
	{"area_code": "406", "iana_timezone": "America/Denver"},
	{"area_code": "407", "iana_timezone": "America/New_York"},
	{"area_code": "408", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "409", "iana_timezone": "America/Chicago"},
	{"area_code": "410", "iana_timezone": "America/New_York"},
	{"area_code": "412", "iana_timezone": "America/New_York"},
	{"area_code": "413", "iana_timezone": "America/New_York"},
	{"area_code": "414", "iana_timezone": "America/Chicago"},
	{"area_code": "415", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "417", "iana_timezone": "America/Chicago"},
	{"area_code": "419", "iana_timezone": "America/New_York"},
	{"area_code": "423", "iana_timezone": "America/New_York"},
	{"area_code": "424", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "425", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "432", "iana_timezone": "America/Chicago"},
	{"area_code": "434", "iana_timezone": "America/New_York"},
	{"area_code": "435", "iana_timezone": "America/Denver"},
	{"area_code": "440", "iana_timezone": "America/New_York"},
	{"area_code": "442", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "443", "iana_timezone": "America/New_York"},
	{"area_code": "458", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "469", "iana_timezone": "America/Chicago"},
	{"area_code": "478", "iana_timezone": "America/New_York"},
	{"area_code": "479", "iana_timezone": "America/Chicago"},
	{"area_code": "480", "iana_timezone": "America/Phoenix"},
	{"area_code": "484", "iana_timezone": "America/New_York"},
	{"area_code": "501", "iana_timezone": "America/Chicago"},
	{"area_code": "502", "iana_timezone": "America/New_York"},
	{"area_code": "503", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "504", "iana_timezone": "America/Chicago"},
	{"area_code": "505", "iana_timezone": "America/Denver"},
	{"area_code": "507", "iana_timezone": "America/Chicago"},
	{"area_code": "508", "iana_timezone": "America/New_York"},
	{"area_code": "509", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "510", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "512", "iana_timezone": "America/Chicago"},
	{"area_code": "513", "iana_timezone": "America/New_York"},
	{"area_code": "515", "iana_timezone": "America/Chicago"},
	{"area_code": "516", "iana_timezone": "America/New_York"},
	{"area_code": "517", "iana_timezone": "America/Detroit"},
	{"area_code": "518", "iana_timezone": "America/New_York"},
	{"area_code": "520", "iana_timezone": "America/Phoenix"},
	{"area_code": "530", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "531", "iana_timezone": "America/Chicago"},
	{"area_code": "539", "iana_timezone": "America/Chicago"},
	{"area_code": "540", "iana_timezone": "America/New_York"},
	{"area_code": "541", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "551", "iana_timezone": "America/New_York"},
	{"area_code": "559", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "561", "iana_timezone": "America/New_York"},
	{"area_code": "562", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "563", "iana_timezone": "America/Chicago"},
	{"area_code": "567", "iana_timezone": "America/New_York"},
	{"area_code": "570", "iana_timezone": "America/New_York"},
	{"area_code": "571", "iana_timezone": "America/New_York"},
	{"area_code": "573", "iana_timezone": "America/Chicago"},
	{"area_code": "574", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "575", "iana_timezone": "America/Denver"},
	{"area_code": "580", "iana_timezone": "America/Chicago"},
	{"area_code": "585", "iana_timezone": "America/New_York"},
	{"area_code": "586", "iana_timezone": "America/Detroit"},
	{"area_code": "601", "iana_timezone": "America/Chicago"},
	{"area_code": "602", "iana_timezone": "America/Phoenix"},
	{"area_code": "603", "iana_timezone": "America/New_York"},
	{"area_code": "605", "iana_timezone": "America/Chicago"},
	{"area_code": "606", "iana_timezone": "America/New_York"},
	{"area_code": "607", "iana_timezone": "America/New_York"},
	{"area_code": "608", "iana_timezone": "America/Chicago"},
	{"area_code": "609", "iana_timezone": "America/New_York"},
	{"area_code": "610", "iana_timezone": "America/New_York"},
	{"area_code": "612", "iana_timezone": "America/Chicago"},
	{"area_code": "614", "iana_timezone": "America/New_York"},
	{"area_code": "615", "iana_timezone": "America/Chicago"},
	{"area_code": "616", "iana_timezone": "America/Detroit"},
	{"area_code": "617", "iana_timezone": "America/New_York"},
	{"area_code": "618", "iana_timezone": "America/Chicago"},
	{"area_code": "619", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "620", "iana_timezone": "America/Chicago"},
	{"area_code": "623", "iana_timezone": "America/Phoenix"},
	{"area_code": "626", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "628", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "629", "iana_timezone": "America/Chicago"},
	{"area_code": "630", "iana_timezone": "America/Chicago"},
	{"area_code": "631", "iana_timezone": "America/New_York"},
	{"area_code": "636", "iana_timezone": "America/Chicago"},
	{"area_code": "641", "iana_timezone": "America/Chicago"},
	{"area_code": "646", "iana_timezone": "America/New_York"},
	{"area_code": "650", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "651", "iana_timezone": "America/Chicago"},
	{"area_code": "657", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "660", "iana_timezone": "America/Chicago"},
	{"area_code": "661", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "662", "iana_timezone": "America/Chicago"},
	{"area_code": "667", "iana_timezone": "America/New_York"},
	{"area_code": "669", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "678", "iana_timezone": "America/New_York"},
	{"area_code": "681", "iana_timezone": "America/New_York"},
	{"area_code": "682", "iana_timezone": "America/Chicago"},
	{"area_code": "701", "iana_timezone": "America/Chicago"},
	{"area_code": "702", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "703", "iana_timezone": "America/New_York"},
	{"area_code": "704", "iana_timezone": "America/New_York"},
	{"area_code": "706", "iana_timezone": "America/New_York"},
	{"area_code": "707", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "708", "iana_timezone": "America/Chicago"},
	{"area_code": "712", "iana_timezone": "America/Chicago"},
	{"area_code": "713", "iana_timezone": "America/Chicago"},
	{"area_code": "714", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "715", "iana_timezone": "America/Chicago"},
	{"area_code": "716", "iana_timezone": "America/New_York"},
	{"area_code": "717", "iana_timezone": "America/New_York"},
	{"area_code": "718", "iana_timezone": "America/New_York"},
	{"area_code": "719", "iana_timezone": "America/Denver"},
	{"area_code": "720", "iana_timezone": "America/Denver"},
	{"area_code": "724", "iana_timezone": "America/New_York"},
	{"area_code": "725", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "727", "iana_timezone": "America/New_York"},
	{"area_code": "731", "iana_timezone": "America/Chicago"},
	{"area_code": "732", "iana_timezone": "America/New_York"},
	{"area_code": "734", "iana_timezone": "America/Detroit"},
	{"area_code": "737", "iana_timezone": "America/Chicago"},
	{"area_code": "740", "iana_timezone": "America/New_York"},
	{"area_code": "743", "iana_timezone": "America/New_York"},
	{"area_code": "747", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "754", "iana_timezone": "America/New_York"},
	{"area_code": "757", "iana_timezone": "America/New_York"},
	{"area_code": "760", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "762", "iana_timezone": "America/New_York"},
	{"area_code": "763", "iana_timezone": "America/Chicago"},
	{"area_code": "765", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "769", "iana_timezone": "America/Chicago"},
	{"area_code": "770", "iana_timezone": "America/New_York"},
	{"area_code": "772", "iana_timezone": "America/New_York"},
	{"area_code": "773", "iana_timezone": "America/Chicago"},
	{"area_code": "774", "iana_timezone": "America/New_York"},
	{"area_code": "775", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "779", "iana_timezone": "America/Chicago"},
	{"area_code": "781", "iana_timezone": "America/New_York"},
	{"area_code": "785", "iana_timezone": "America/Chicago"},
	{"area_code": "786", "iana_timezone": "America/New_York"},
	{"area_code": "801", "iana_timezone": "America/Denver"},
	{"area_code": "802", "iana_timezone": "America/New_York"},
	{"area_code": "803", "iana_timezone": "America/New_York"},
	{"area_code": "804", "iana_timezone": "America/New_York"},
	{"area_code": "805", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "806", "iana_timezone": "America/Chicago"},
	{"area_code": "808", "iana_timezone": "Pacific/Honolulu"},
	{"area_code": "810", "iana_timezone": "America/Detroit"},
	{"area_code": "812", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "813", "iana_timezone": "America/New_York"},
	{"area_code": "814", "iana_timezone": "America/New_York"},
	{"area_code": "815", "iana_timezone": "America/Chicago"},
	{"area_code": "816", "iana_timezone": "America/Chicago"},
	{"area_code": "817", "iana_timezone": "America/Chicago"},
	{"area_code": "818", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "828", "iana_timezone": "America/New_York"},
	{"area_code": "830", "iana_timezone": "America/Chicago"},
	{"area_code": "831", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "832", "iana_timezone": "America/Chicago"},
	{"area_code": "843", "iana_timezone": "America/New_York"},
	{"area_code": "845", "iana_timezone": "America/New_York"},
	{"area_code": "847", "iana_timezone": "America/Chicago"},
	{"area_code": "848", "iana_timezone": "America/New_York"},
	{"area_code": "850", "iana_timezone": "America/Chicago"},
	{"area_code": "854", "iana_timezone": "America/New_York"},
	{"area_code": "856", "iana_timezone": "America/New_York"},
	{"area_code": "857", "iana_timezone": "America/New_York"},
	{"area_code": "858", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "859", "iana_timezone": "America/New_York"},
	{"area_code": "860", "iana_timezone": "America/New_York"},
	{"area_code": "862", "iana_timezone": "America/New_York"},
	{"area_code": "863", "iana_timezone": "America/New_York"},
	{"area_code": "864", "iana_timezone": "America/New_York"},
	{"area_code": "865", "iana_timezone": "America/New_York"},
	{"area_code": "870", "iana_timezone": "America/Chicago"},
	{"area_code": "878", "iana_timezone": "America/New_York"},
	{"area_code": "901", "iana_timezone": "America/Chicago"},
	{"area_code": "903", "iana_timezone": "America/Chicago"},
	{"area_code": "904", "iana_timezone": "America/New_York"},
	{"area_code": "907", "iana_timezone": "America/Anchorage"},
	{"area_code": "908", "iana_timezone": "America/New_York"},
	{"area_code": "909", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "910", "iana_timezone": "America/New_York"},
	{"area_code": "912", "iana_timezone": "America/New_York"},
	{"area_code": "913", "iana_timezone": "America/Chicago"},
	{"area_code": "914", "iana_timezone": "America/New_York"},
	{"area_code": "915", "iana_timezone": "America/Denver"},
	{"area_code": "916", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "917", "iana_timezone": "America/New_York"},
	{"area_code": "918", "iana_timezone": "America/Chicago"},
	{"area_code": "919", "iana_timezone": "America/New_York"},
	{"area_code": "920", "iana_timezone": "America/Chicago"},
	{"area_code": "925", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "928", "iana_timezone": "America/Phoenix"},
	{"area_code": "929", "iana_timezone": "America/New_York"},
	{"area_code": "930", "iana_timezone": "America/Indiana/Indianapolis"},
	{"area_code": "931", "iana_timezone": "America/Chicago"},
	{"area_code": "936", "iana_timezone": "America/Chicago"},
	{"area_code": "937", "iana_timezone": "America/New_York"},
	{"area_code": "940", "iana_timezone": "America/Chicago"},
	{"area_code": "941", "iana_timezone": "America/New_York"},
	{"area_code": "947", "iana_timezone": "America/Detroit"},
	{"area_code": "949", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "951", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "952", "iana_timezone": "America/Chicago"},
	{"area_code": "954", "iana_timezone": "America/New_York"},
	{"area_code": "956", "iana_timezone": "America/Chicago"},
	{"area_code": "959", "iana_timezone": "America/New_York"},
	{"area_code": "970", "iana_timezone": "America/Denver"},
	{"area_code": "971", "iana_timezone": "America/Los_Angeles"},
	{"area_code": "972", "iana_timezone": "America/Chicago"},
	{"area_code": "973", "iana_timezone": "America/New_York"},
	{"area_code": "978", "iana_timezone": "America/New_York"},
	{"area_code": "979", "iana_timezone": "America/Chicago"},
	{"area_code": "980", "iana_timezone": "America/New_York"},
	{"area_code": "984", "iana_timezone": "America/New_York"},
	{"area_code": "985", "iana_timezone": "America/Chicago"},
	{"area_code": "989", "iana_timezone": "America/Detroit"},
]

SEED_SQL = """
	INSERT INTO us_area_code_timezones (area_code, iana_timezone)
	VALUES (:area_code, :iana_timezone)
	ON CONFLICT (area_code) DO NOTHING
"""


def main() -> int:
	with get_owner_db_context() as db:
		for stmt in DDL:
			db.execute(text(stmt))
		for row in SEED_AREA_CODES:
			db.execute(text(SEED_SQL), row)
		db.commit()
		count = db.execute(text("SELECT count(*) FROM us_area_code_timezones")).scalar()
	print(f"apply_area_code_timezones: done — {count} area codes present")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
